export {
  HomeIcon,
  DirectIcon,
  NewPostIcon,
  ExploreIcon,
  ActiveIcon,
  FavoriteIcon,
  CommentIcon,
  MarkIcon,
  SeeMoreIcon,
  EmoticonIcon,
  SearchIcon,
  ProfileIcon,
  SettingIcon,
  AddIcon,
  BackIcon,
  ImageVideoIcon,
  DeleteIcon,
} from './Icon';